export const styles = {
    button: {
        display: "inline-block",
        background: "transparent",
        color: 'inherit',
        font: "inherit",
        border: 0,
        outline: 0,
        padding: 0,
        transition: "all 200ms ease-in",
        cursor: "pointer",
    },
    button_add: {
        background: "#7f8ff4",
        color: "#fff",
        "box-shadow": "0 0 10px 2px rgba(0, 0, 0, 0.1)",
        "border-radius": "2px",
        padding: "22px 15px",
        "margin-left": "-62px",
    },
    section: {
        width: "320px",
        background: "#fff",
        color: "#000000",
        font: "inherit",
        "box-shadow": "0 6px 10px 0 rgba(0, 0, 0, 0.1)",
        border: 0,
        outline: 0,
        "border-radius": "2px",
        padding: "22px 18px",
        "line-height": "8px",
    },
}