export const styles = {
    todo_item: {
        position: "relative",
        left: "24%",
        margin: "10px",
        height: "50px"
    },
    button: {
        display: "inline-block",
        background: "transparent",
        color: 'inherit',
        font: "inherit",
        border: 0,
        outline: 0,
        padding: 0,
        transition: "all 200ms ease-in",
        cursor: "pointer",
    },
    button_checkbox: {
        position: "relative",
        left: "202px",
        bottom: "29px",
        height: "50px",
        width: "50px",
        background: "#89f885",
        color: "#fff",
        "box-shadow": "0 0 10px 2px rgba(0, 0, 0, 0.1)",
        "border-radius": "2px",
        padding: "22px 15px",
        "font-size": "30px",
    },
    button_delete: {
        position: "relative",
        left: "202px",
        bottom: "31px",
        height: "50px",
        width: "50px",
        background: "#fa5656",
        color: "#fff",
        "box-shadow": "0 0 10px 2px rgba(0, 0, 0, 0.1)",
        "border-radius": "2px",
        padding: "22px 15px",
        "font-size": "25px",
    },
    section: {
        width: "320px",
        background: "#fff",
        color: "#000000",
        font: "inherit",
        "box-shadow": "0 6px 10px 0 rgba(0, 0, 0, 0.1)",
        border: 0,
        outline: 0,
        "border-radius": "2px",
        padding: "22px 18px",
        "line-height": "8px",
    },
    section_checked: {
        width: "320px",
        background: "#fff",
        color: "#bebebe",
        font: "inherit",
        "box-shadow": "0 6px 10px 0 rgba(0, 0, 0, 0.1)",
        border: 0,
        outline: 0,
        "border-radius": "2px",
        padding: "22px 18px",
        "line-height": "8px",
        "text-decoration-line": "line-through",
    }
}